version: '3.8'
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27027"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: backend22
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb://mongodb:27017"

volumes:
  mongodb_data: 

